version: "3"
services:
  redis:
    image: redis
    command: "redis-server"
    container_name: cache
    expose:
      - 6379
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    container_name: db
    expose:
      - 5432
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - PORT=8080
      - DATABASE_URL=postgres://postgres:1@db:5432/base
      - REDIS_URL=redis://cache:6379
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - "postgres"
      - "redis"
    stdin_open: true
    tty: true
    command: bash -c "yarn start:dev"
